"""Writes THIRD-PARTY-NOTICES.txt for everything linked into praetervnc.exe."""
import json, os, re, subprocess

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'THIRD-PARTY-NOTICES.txt')
LICENSE_FILE = re.compile(r'^(licen[cs]e|copying|notice)', re.I)


def metadata():
    out = subprocess.run(['cargo', 'metadata', '--format-version', '1', '--filter-platform', 'x86_64-pc-windows-msvc'],
                         cwd=ROOT, check=True, capture_output=True, encoding='utf-8').stdout
    return json.loads(out)


def shipped(meta):
    """Normal (non-build, non-dev) dependencies of praetervnc, excluding proc-macros."""
    pkgs = {p['id']: p for p in meta['packages']}
    nodes = {n['id']: n for n in meta['resolve']['nodes']}
    root = next(i for i, p in pkgs.items() if p['name'] == 'praetervnc')
    seen, todo = set(), [root]
    while todo:
        i = todo.pop()
        for d in nodes[i]['deps']:
            if not any(k['kind'] is None for k in d['dep_kinds']) or d['pkg'] in seen:
                continue
            if any('proc-macro' in t['kind'] for t in pkgs[d['pkg']]['targets']):
                continue
            seen.add(d['pkg'])
            todo.append(d['pkg'])
    return sorted((pkgs[i] for i in seen), key=lambda p: p['name'])


def license_files(p):
    d = os.path.dirname(p['manifest_path'])
    files = sorted(f for f in os.listdir(d) if LICENSE_FILE.match(f) and os.path.isfile(os.path.join(d, f)))
    expr = (p.get('license') or '').replace('/', ' OR ')
    if ' OR ' in expr and 'MIT' in expr.split(' OR '):
        mit = [f for f in files if 'mit' in f.lower()]
        files = mit or [f for f in files if 'apache' not in f.lower()] or files
    return [os.path.join(d, f) for f in files]


def read(path):
    return open(path, encoding='utf-8', errors='replace').read().replace('\r\n', '\n').strip()


def ijg_legal(readme):
    m = re.search(r'^LEGAL ISSUES\n=+\n(.*?)\n\n(?=[A-Z][A-Z ]+\n=+)', read(readme), re.S | re.M)
    return m.group(1).strip() if m else read(readme)


def main():
    pkgs = shipped(metadata())
    out = ['PraeterVNC includes the third-party software listed below. Generated by tools/notices.py.', '']
    texts = {}
    for p in pkgs:
        d = os.path.dirname(p['manifest_path'])
        if p['name'] == 'turbojpeg-sys':
            lj = os.path.join(d, 'libjpeg-turbo')
            body = ['This software is based in part on the work of the Independent JPEG Group.', '',
                    read(os.path.join(lj, 'LICENSE.md')), '', 'The IJG License (from README.ijg):', '',
                    ijg_legal(os.path.join(lj, 'README.ijg'))]
            texts.setdefault('\n'.join(body), []).append('libjpeg-turbo (bundled in turbojpeg-sys)')
        if p['name'] == 'libmimalloc-sys':
            for v in ('v2', 'v3'):
                f = os.path.join(d, 'c_src', 'mimalloc', v, 'LICENSE')
                if os.path.exists(f):
                    texts.setdefault(read(f), []).append(f'mimalloc C library {v} (bundled in libmimalloc-sys)')
        for f in license_files(p):
            texts.setdefault(read(f), []).append(f"{p['name']} {p['version']}")

    out.append('Rust crates')
    out.append('-' * 11)
    w = max(len(f"{p['name']} {p['version']}") for p in pkgs)
    for p in pkgs:
        nv = f"{p['name']} {p['version']}"
        out.append(f"{nv:<{w}}  {p.get('license') or '?'}  {p.get('repository') or ''}".rstrip())
    out.append('')
    for text, users in texts.items():
        out += ['=' * 78, 'Applies to: ' + ', '.join(users), '=' * 78, '', text, '']
    open(OUT, 'w', encoding='utf-8', newline='\n').write('\n'.join(out))
    unlicensed = [p['name'] for p in pkgs if not license_files(p)]
    print(f'{OUT}: {len(pkgs)} crates, {len(texts)} license texts; no license file: {", ".join(unlicensed) or "none"}')


if __name__ == '__main__':
    main()
